Repository jenkinsci/gson-api-plugin, pull requests merged in 2024-08, with the labels that each got.

#34 Remove hard-coded java-version in Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#35 Automated PR
  pom.xml
Labels: dependencies

#39 Applied recipes AddPluginsBom, UpgradeBomVersion
  pom.xml
Labels: dependencies, chore

#40 Applied recipes UpgradeBomVersion, UpgradeParentVersion
  pom.xml
Labels: dependencies
